### ISSUE TITLE
redirectUrl() doesn't reload the snippet

### ISSUE THREAD

**Issue by medhi** [vojtech-dobes/history.nette.ajax.js#19]
A have a signal. 

If I use `$this->redirect('Article:default', ["id" => 22])`, it works. 

But if I use `$this->redirectUrl('/article/22')`, URL will change, but snippet doesn't reload.

The response contains only `redirect: "/general/comment/22"`, nothing more.

**Comment by vojtech-dobes** [comment]
> The response contains only redirect: "/general/comment/22", nothing more.

And if you disable history extension (serverside), is `/general/comment/22` in payload too also for `redirect('Art...` call?

**Comment by medhi** [comment]
First, I have a mistake above, it should be: 

> The response contains only redirect: "/article/22", nothing more.

Sorry for that.

It is quite time, I tried it now and it seems working. Can't reproduce the problem.
